# Generated by Django 4.2.14 on 2024-07-28 20:06

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("auctions", "0005_alter_auctionlisting_category_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="auctionlisting",
            name="watchlist",
            field=models.ManyToManyField(
                blank=True,
                null=True,
                related_name="listing_watchlist",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
