# Generated by Django 4.2.11 on 2024-07-29 09:42

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("auctions", "0006_auctionlisting_watchlist"),
    ]

    operations = [
        migrations.AlterField(
            model_name="auctionlisting",
            name="watchlist",
            field=models.ManyToManyField(
                blank=True,
                related_name="listing_watchlist",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
