# Generated by Django 4.2.11 on 2024-07-30 11:22

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("auctions", "0010_bid_alter_auctionlisting_starting_bid"),
    ]

    operations = [
        migrations.AlterField(
            model_name="bid",
            name="bid",
            field=models.IntegerField(default=0),
        ),
    ]
