# Generated by Django 4.2.11 on 2024-07-30 13:25

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("auctions", "0011_alter_bid_bid"),
    ]

    operations = []
